services:

  chatcat:
    container_name: chatcat
    image: inveracity/chatcat:latest
    build:
      dockerfile: docker/chatcat.dockerfile
      context: .
    working_dir: /build
    command: ["bun", "run", "index.js"]
    ports:
      - 3000:3000
    volumes:
      - ./data/:/build/data
    environment:
      - "ORIGIN=http://localhost:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.ui.rule=Host(`chat.christopherbaklid.com`)
      - traefik.http.routers.ui.entrypoints=websecure
      - traefik.http.routers.ui.tls.certresolver=myresolver
      - traefik.http.routers.ui.tls=true
    restart: "unless-stopped"
